#include "FileManager.h"
#include "Document.h"
#include "layers/Layer.h"
#include "shapes/ShapeBase.h"
#include <QFile>
#include <QJsonDocument>
#include <QJsonObject>
#include <QJsonArray>
#include <QGraphicsScene>
#include <QSvgGenerator>
#include <QImage>
#include <QPainter>

FileManager::FileManager(QObject *parent)
    : QObject(parent)
{
}

bool FileManager::saveDocument(const QString &path, Document *document)
{
    if (!document) return false;

    QJsonObject docObj = document->toJson();

    QJsonDocument jsonDoc(docObj);
    QFile file(path);
    if (!file.open(QIODevice::WriteOnly | QIODevice::Text)) {
        return false;
    }

    file.write(jsonDoc.toJson(QJsonDocument::Indented));
    file.close();
    addRecentFile(path);
    return true;
}

Document *FileManager::loadDocument(const QString &path)
{
    QFile file(path);
    if (!file.open(QIODevice::ReadOnly | QIODevice::Text)) {
        return nullptr;
    }

    QByteArray data = file.readAll();
    file.close();

    QJsonParseError error;
    QJsonDocument jsonDoc = QJsonDocument::fromJson(data, &error);
    if (error.error != QJsonParseError::NoError) {
        return nullptr;
    }

    Document *doc = Document::fromJson(jsonDoc.object());
    if (doc) {
        addRecentFile(path);
    }
    return doc;
}

bool FileManager::exportSvg(const QString &path, QGraphicsScene *scene)
{
    if (!scene) return false;

    QRectF sceneRect = scene->itemsBoundingRect().adjusted(-20, -20, 20, 20);
    if (sceneRect.isEmpty()) sceneRect = QRectF(0, 0, 800, 600);

    QSvgGenerator generator;
    generator.setFileName(path);
    generator.setSize(sceneRect.size().toSize());
    generator.setViewBox(sceneRect);
    generator.setTitle("Paint Export");
    generator.setDescription("Generated by Paint - Lightweight Vector Drawing");

    QPainter painter;
    painter.begin(&generator);
    painter.setRenderHint(QPainter::Antialiasing);
    scene->render(&painter, QRectF(), sceneRect);
    painter.end();

    return true;
}

bool FileManager::exportPng(const QString &path, QGraphicsScene *scene)
{
    if (!scene) return false;

    QRectF sceneRect = scene->itemsBoundingRect().adjusted(-20, -20, 20, 20);
    if (sceneRect.isEmpty()) sceneRect = QRectF(0, 0, 800, 600);

    QImage image(sceneRect.size().toSize() * 2, QImage::Format_ARGB32_Premultiplied);
    image.fill(Qt::white);

    QPainter painter(&image);
    painter.setRenderHint(QPainter::Antialiasing);
    painter.setRenderHint(QPainter::SmoothPixmapTransform);
    scene->render(&painter, image.rect(), sceneRect);
    painter.end();

    return image.save(path, "PNG");
}

void FileManager::addRecentFile(const QString &path)
{
    m_recentFiles.removeAll(path);
    m_recentFiles.prepend(path);
    while (m_recentFiles.size() > MAX_RECENT_FILES) {
        m_recentFiles.removeLast();
    }
}
